name = "FixedPoint"
uuid = "3325f569-5a18-4e7d-8356-246b69339eea"
authors = ["Francesco Alemanno <francescoalemanno710@gmail.com>"]
version = "1.0.1"

[compat]
julia = "^1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
